services:
  app:
    image: ${IMAGE_FULL_NAME}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf  # 前端用
      - ${LOG_DIR}:/var/log/nginx
    environment:
      - TZ=Asia/Shanghai
    networks:
      - app_network

networks:
  app_network:
    name: ${NETWORK_NAME}
    external: true
