name: 01-手动打包镜像

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: '请输入版本号 (例如 v1.0.1)'
        required: true
        default: 'v1.0.0'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: 1. 拉取代码
        uses: actions/checkout@v4

      - name: 2. 登录 GitHub 镜像库
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 3. 构建并推送镜像
        run: |
          # 转换镜像名为全小写 (GHCR 强制要求)
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=${{ github.event.inputs.version_tag }}
          
          echo "镜像名称: $IMAGE_ID"
          echo "版本标签: $VERSION"

          # 构建镜像
          docker build . --file Dockerfile -t $IMAGE_ID:$VERSION -t $IMAGE_ID:latest
          
          # 推送指定版本和 latest 版本
          docker push $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:latest
