name: Deploy to Server

on:
  workflow_dispatch: # 手动触发部署
    inputs:
          manual_tag:
            description: '【可选】手动指定镜像 Tag (如: sha-1663e5d)。留空则自动按分支或tag Hash 部署。'
            required: false
            default: ''
            
jobs:
  deploy:
    runs-on: [self-hosted, jinan-1]
      
    steps:
      - name: 1. 拉取代码
        uses: actions/checkout@v4

      # ✨ tr '[A-Z]' '[a-z]' 逻辑
      - name: 2. 提取镜像元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            # 自动处理 sha-xxxxxxx 格式
            type=sha,format=short,prefix=sha-
            # 如果是 Tag 触发，自动处理 v1.2.3 格式
            type=ref,event=tag

      # ✨ docker login 逻辑
      - name: 3. 登录 GitHub 镜像库
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 4. 执行部署
        run: |
          # 1. 变量准备
          REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[A-Z]' '[a-z]')
          OWNER_NAME=$(echo "${{ github.repository_owner }}" | tr '[A-Z]' '[a-z]')
          DEPLOY_DIR="/data1/${REPO_NAME}"

          if [ -n "${{ github.event.inputs.manual_tag }}" ]; then
            IMAGE_FULL_NAME="ghcr.io/${OWNER_NAME}/${REPO_NAME}:${{ github.event.inputs.manual_tag }}"
          else
            IMAGE_FULL_NAME="${{ fromJson(steps.meta.outputs.json).tags[0] }}"
          fi
          IMAGE_FULL_NAME=$(echo "$IMAGE_FULL_NAME" | tr '[A-Z]' '[a-z]')

          echo "🚀 准备部署镜像: ${IMAGE_FULL_NAME}"

          # 2. 目录同步与文件准备
          mkdir -p "$DEPLOY_DIR"
          # 预拉取镜像减少停机时间
          docker pull ${IMAGE_FULL_NAME}
          
          echo "🔄 同步代码文件到 ${DEPLOY_DIR}..."
          rsync -avz --delete --exclude '.git' --exclude '.env*' ./ ${DEPLOY_DIR}/
          
          cd ${DEPLOY_DIR}

          # 3. 写入环境变量
          echo "IMAGE_FULL_NAME=${IMAGE_FULL_NAME}" > .env.image
          printf "%b" "${{ secrets.ENV_FILE_CONTENT }}" > .env

          # 4. 执行启动 (注入变量)
          echo "🐳 启动 Docker 容器..."
          IMAGE_FULL_NAME=${IMAGE_FULL_NAME} docker compose up -d --force-recreate

          # 5. 清理一周前的旧镜像
          docker image prune -af --filter "until=168h"